name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: size-limit - beamwind
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install
          directory: packages/beamwind
